before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - echo %PATH%
#copy timapi JAR because it is not on github
  - cp ../../../../../timapi* ./

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build

  
build:
  stage: build
  script:
    - gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - gradlew test
    - mv build\reports\tests\test public/
  artifacts:
    paths:
      - public
    reports:
      junit: build/test-results/test/TEST-*.xml

after_script:
  - echo "End CI"