before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - set GRADLE_USER_HOME=C:/Users/mmu/.gradle
  - set JAVA_HOME=C:/Program Files (x86)/Java/jdk1.8.0
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - echo %PATH%
    - gradle check

deploy:
  stage: deploy
  script:
    - ./deploy

after_script:
  - echo "End CI"