before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=C:/Users/mmu/.gradle
  - export PATH=C:/Users/mmu/Downloads/gradle-4.10.2-bin/gradle-4.10.2/bin/;$PATH
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradle check

deploy:
  stage: deploy
  script:
    - ./deploy

after_script:
  - echo "End CI"